# Generated by Django 3.0 on 2021-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_allproduct_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_products'),
        ),
        migrations.AddField(
            model_name='allproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='allproduct',
            name='unit',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
