# Generated by Django 3.0 on 2021-10-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211006_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproduct',
            old_name='photo',
            new_name='image',
        ),
    ]
