# Generated by Django 3.0 on 2021-10-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cart_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='dafaultprofile.png', null=True, upload_to='gallery_photo_profile'),
        ),
    ]
