# Generated by Django 3.0 on 2021-10-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_orderlist_orderpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='sliptime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
