# Generated by Django 3.0 on 2021-10-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_orderpending_sliptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='other',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
